image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-ibank-build-for-testers.jar -P:profile=test&
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
